name: Deploy to Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Storage
        run: |
          gsutil -m rsync -r ./frontend/* gs://datafromfile.com
